---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBCnSgLOiOm2z7XG3dMB1USaY7owpsK2QNAefG/FJ4aahho9A8kDQRww1YFg9Xg9KJ1Z33I0y9BosNTKiu2/DMTChSr7jstKJEl9VvezfZyRJBnw+WFvF3ksDkLEsK4iYGeXku62o+5MviyC6lzs1QY9f9NfyQrfHbqszpsg43Hg+C09DqrHLONTfZgLd5mKIo0L1dwxlxYOE0E9yiq9/e5LvBxW/EkU9q1+HgLV5xd/C6rf3pLY2oEOKt0q3e886B3qVOSgn3gNyksRQ8IKqAfkvtq/DNDMWx2jQO2Bpk62m8czZlXoRnX/58Fp29EclRUF7OT5U9Vbi9i9N4EFIG1JRlNdwbILy7bq6Ckwj6IoSKbhwL/CkKGcHEpBaI+cGaO9cbdzqToTNtyuzAtIU7wUMKhKD+lBsjK8irFUtSS0eazV/wNAxu9LuQhHfuVXlK11ck5AFn9SMSn8Lv+Ycij2fqtLTDbvVDyR/AbjXMeUaPz4RS0AniThAQOS0Q5lWG0bk+6gOtJMQsfhLVyEzaxOJuLxVQFR1+lL43vV5tzIvbEoG95LPWQXZhrPYwEbvywJEO4dLq1VRYVVAWOuWzWSY22IflnJCWdROXMg/olRPpQg6flPG9M9EUVwG7/fOWwI2aIGANp0yjMcrj6tXC5XFa3y3ZVeFSC4xP/VrhKISt9r1q5xlqJOcLnZBV4P1F3wWxMo/ixfQ+SEk7iNpOr8BwKqH7ju3JVJDUaw/xKwg==
    admin-user: AgBmbRs4VYzUnfHxW2o1IjbFTMSAbJs8mmbnHpGE0MKbmhmreGcaSEuVFt0esiValNji86Xr4jN5MdSstkF/NS7mqUi116f8VWwPa2AuhcLONtI7IKyDMHbP7drmb7K/mrr33uMXon2KAj58y0M26CoSqSGEBtnJDqzrz3/V6FSm1Sa3JPj2ntwyK2U02u8LJ6k58qY9hIl8jYUubvzGhkdWFmXg2Susx65Nelw1J4sFjJ3Yt3Jhx4LzyknHrtcfUJO69plDroHEqOKIW2NpoKPiuF8FGq8sHOzJVFj42EQHe2ZK2oFQ3wF5s/OxIQ/sYIdn6HP6gdUoJaoT88dokSW+lUopxBwL1qkgESc+Si4tuTTqUOyBQdZGhN5OKDeqfvsi4SO+tDtYvSdTLPiFzGX3q3SkDXfqnVjUGMIX7Bbn9F2herPEA+GXxc1La3OOlcrxhbdHgHICmXaS+U3Yq0f2R1JZGh1kF5ciPbfrf31lFqRjndQXuqGXmR3wXreyhGxMMrYRcH4G3uYoilOhhGL96pI3i84Q0n8fRK1nV3FjKryw88rC+3GqwmD1ZK9EythnF5SCz9gIz1lNQKAUQBv+n2acl9vgeHBxVtHMk9G4X+Y3zCfTu74eK4HyGCCkxiTmKSc/iSU1cU4o0nRKARsZxPET/egPF1k0gz6VnluWu2B8nVbCtGFpFX22B5TPI195tSdqMA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
