---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: todo
spec:
  encryptedData:
    password: AgCYyQGqmQW1NwsYgtZy5dA/wVov1d5Txtrk80rdqGPPIEzzM1Ldzvu+vznq+/OB5Cv1TJ/spLGtCHnwpD3AitjiI2eb8+/Sn+KHapKYgmFHzYCONSVClquvC8O9jlPJU5g3AnvlhAgdMhkxzOdhFpU7huI2vVkCoUilrPy61WmtPHZByePEcjB5iBoJDcUO42sW+DsJVHAfARyNvWX9P88fwZibcMpYVC3Lb4vXsh/peJeyruRL0sid7cBPmtmeeJKStwADtXqiRjh9Qcps4e9FFU5tiPOLnbqCqsoGGJ+18/tpjVJnZgfvd/Z2B38jDx9d7g4ZdTNNTIMwPsKnFyd6rTo7uV6tmFvrbnyN6/5rQRNnrknWwU1qt58uidNTornHQ+u493VDD3k7PuzRBwALu9niMc3uDKvpSu1fTAEYwxr/m7Z4zR8xvGWBApgY82c0zl0Nuwfw60kPpH0fTV32L97iHPkoK6GkpAnclq8bjCtf0aVTzea6N7dkrQEAG0tuZwXNdZ1RB/57imRjaqUGBjk6eHv+QseG/26e1EQ3dWVhZhpLRrNXN/113Nra6EiGi8n6DhjWbRquj7Ge9MXNcr1Ol3Am2c0LmoIohOd35g8aU0TSRG6NuyoFwm18BN6K9/8IusU3CglgYFJVLPoLMUenuhyr8ALOXSHM/4jyqRNKVWuFxPC7XBM+myXVk8rtgvvkEjLgVg8444C0mJONnJm2Ss5VzMjsS+aqWv9oFQ==
  template:
    metadata:
      name: redis-secret
      namespace: todo
