apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 87.19.0
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        prometheus-windows-exporter:
          enabled: false
        prometheus:
          prometheusSpec:
            retention: 6h
            storageSpec:
              volumeClaimTemplate:
                spec:
                  resources:
                    requests:
                      storage: 10Gi
        grafana:
          admin:
            existingSecret: grafana-admin-credentials
            userKey: admin-user
            passwordKey: admin-password
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki.monitoring.svc.cluster.local:3100
              access: proxy
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.192.168.80.169.nip.io
            tls:
              - secretName: grafana-tls
                hosts:
                  - grafana.192.168.80.169.nip.io
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
